
// This file has been generated by the GUI designer. Do not modify.
namespace Destrospean.DestrospeanCASPEditor
{
	public partial class ChooseObjectDialog
	{
		private global::Gtk.ScrolledWindow ScrolledWindow;
		
		private global::Gtk.IconView IconView;
		
		private global::Gtk.Button CancelButton;
		
		private global::Gtk.Button OKButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Destrospean.DestrospeanCASPEditor.ChooseObjectDialog
			this.WidthRequest = 344;
			this.HeightRequest = 240;
			this.Name = "Destrospean.DestrospeanCASPEditor.ChooseObjectDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Destrospean.DestrospeanCASPEditor.ChooseObjectDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "MainVBox";
			w1.BorderWidth = ((uint)(2));
			// Container child MainVBox.Gtk.Box+BoxChild
			this.ScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.ScrolledWindow.CanFocus = true;
			this.ScrolledWindow.Name = "ScrolledWindow";
			this.ScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child ScrolledWindow.Gtk.Container+ContainerChild
			this.IconView = new global::Gtk.IconView ();
			this.IconView.CanFocus = true;
			this.IconView.Name = "IconView";
			this.IconView.Margin = 2;
			this.ScrolledWindow.Add (this.IconView);
			w1.Add (this.ScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this.ScrolledWindow]));
			w3.Position = 0;
			// Internal child Destrospean.DestrospeanCASPEditor.ChooseObjectDialog.ActionArea
			global::Gtk.HButtonBox w4 = this.ActionArea;
			w4.Name = "ActionArea";
			w4.Spacing = 10;
			w4.BorderWidth = ((uint)(5));
			w4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.CanDefault = true;
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseStock = true;
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = "gtk-cancel";
			this.AddActionWidget (this.CancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4 [this.CancelButton]));
			w5.Expand = false;
			w5.Fill = false;
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.OKButton = new global::Gtk.Button ();
			this.OKButton.CanDefault = true;
			this.OKButton.CanFocus = true;
			this.OKButton.Name = "OKButton";
			this.OKButton.UseStock = true;
			this.OKButton.UseUnderline = true;
			this.OKButton.Label = "gtk-ok";
			this.AddActionWidget (this.OKButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4 [this.OKButton]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 344;
			this.DefaultHeight = 240;
			this.Show ();
		}
	}
}
