
// This file has been generated by the GUI designer. Do not modify.
namespace Destrospean.DestrospeanCASPEditor
{
	public partial class NewUpdateDialog
	{
		private global::Gtk.VBox UpdateAvailableVBox;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Alignment InfoIconAlignment;
		
		private global::Gtk.Image InfoIcon;
		
		private global::Gtk.Label UpdateAvailableLabel;
		
		private global::Gtk.ScrolledWindow ScrolledWindow;
		
		private global::Gtk.TextView ChangelogTextView;
		
		private global::Gtk.Button CancelButton;
		
		private global::Gtk.Button ApplyButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Destrospean.DestrospeanCASPEditor.NewUpdateDialog
			this.WidthRequest = 344;
			this.HeightRequest = 240;
			this.Name = "Destrospean.DestrospeanCASPEditor.NewUpdateDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Update Available");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Destrospean.DestrospeanCASPEditor.NewUpdateDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "MainVBox";
			w1.BorderWidth = ((uint)(2));
			// Container child MainVBox.Gtk.Box+BoxChild
			this.UpdateAvailableVBox = new global::Gtk.VBox ();
			this.UpdateAvailableVBox.Name = "UpdateAvailableVBox";
			this.UpdateAvailableVBox.Spacing = 6;
			// Container child UpdateAvailableVBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.InfoIconAlignment = new global::Gtk.Alignment (1F, 0.5F, 1F, 1F);
			this.InfoIconAlignment.Name = "InfoIconAlignment";
			// Container child InfoIconAlignment.Gtk.Container+ContainerChild
			this.InfoIcon = new global::Gtk.Image ();
			this.InfoIcon.Name = "InfoIcon";
			this.InfoIcon.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Dialog);
			this.InfoIconAlignment.Add (this.InfoIcon);
			this.hbox1.Add (this.InfoIconAlignment);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.InfoIconAlignment]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UpdateAvailableLabel = new global::Gtk.Label ();
			this.UpdateAvailableLabel.Name = "UpdateAvailableLabel";
			this.UpdateAvailableLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Label");
			this.hbox1.Add (this.UpdateAvailableLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.UpdateAvailableLabel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.UpdateAvailableVBox.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.UpdateAvailableVBox [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child UpdateAvailableVBox.Gtk.Box+BoxChild
			this.ScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.ScrolledWindow.Name = "ScrolledWindow";
			this.ScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child ScrolledWindow.Gtk.Container+ContainerChild
			this.ChangelogTextView = new global::Gtk.TextView ();
			this.ChangelogTextView.CanFocus = true;
			this.ChangelogTextView.Name = "ChangelogTextView";
			this.ChangelogTextView.Editable = false;
			this.ChangelogTextView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.ScrolledWindow.Add (this.ChangelogTextView);
			this.UpdateAvailableVBox.Add (this.ScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.UpdateAvailableVBox [this.ScrolledWindow]));
			w7.Position = 1;
			w1.Add (this.UpdateAvailableVBox);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.UpdateAvailableVBox]));
			w8.Position = 0;
			// Internal child Destrospean.DestrospeanCASPEditor.NewUpdateDialog.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.CanDefault = true;
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseStock = true;
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = "gtk-cancel";
			this.AddActionWidget (this.CancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.CancelButton]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.ApplyButton = new global::Gtk.Button ();
			this.ApplyButton.CanDefault = true;
			this.ApplyButton.CanFocus = true;
			this.ApplyButton.Name = "ApplyButton";
			this.ApplyButton.UseStock = true;
			this.ApplyButton.UseUnderline = true;
			this.ApplyButton.Label = "gtk-apply";
			this.AddActionWidget (this.ApplyButton, -10);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.ApplyButton]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 344;
			this.DefaultHeight = 240;
			this.Show ();
		}
	}
}
