name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set lowercase owner name
      run: |
        echo "REPO_LC=${REPO,,}" >> $GITHUB_ENV
      env:
        REPO: ${{ github.repository }}
    - name: Log into registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull Docker image
      run: |
        docker pull ghcr.io/${{env.REPO_LC}}:master
    - name: Build from Docker image
      run: docker run --rm --name casdesignertoolkit -v "$(pwd)":/CASDesignerToolkit ghcr.io/${{env.REPO_LC}} bash -c "/CASDesignerToolkit/tools/build_debian.sh && cd /CASDesignerToolkit/CASDesignerToolkit/bin/Release && rm Newtonsoft.Json.xml OpenTK.xml s3pi*.xml System.Custom.xml TeximpNet.xml && /CASDesignerToolkit/tools/bundle_debian.sh"
    - uses: actions/checkout@v4
    - name: Upload Linux amd64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: CASDesignerToolkit-linux-amd64
        path: CASDesignerToolkit/bin/Release/dist/CASDesignerToolkit-linux-amd64.rar
    - name: Upload Windows i386 artifact
      uses: actions/upload-artifact@v4
      with:
        name: CASDesignerToolkit-win32-i386
        path: CASDesignerToolkit/bin/Release/dist/CASDesignerToolkit-win32-i386.rar
    - name: Upload Windows i386 self-extractor artifact
      uses: actions/upload-artifact@v4
      with:
        name: CASDesignerToolkit-Self-Extractor
        path: CASDesignerToolkit/bin/Release/dist/CASDesignerToolkit-Self-Extractor.exe
